###
# @name jwt_login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "customer1@user.com",
  "password": "secret"
}

###

@jwt_login = {{ jwt_login.response.body.access_token }}

###
GET http://localhost:3000/assets


POST http://localhost:3000/orders
Authorization: Bearer {{ jwt_login }}